=== Zanzibarin/HTML.CSS.XML.Practice/XMLPractice1.2/lessons_DTD.dtd
<!ELEMENT lessons (lesson*)> 
<!ELEMENT lesson (LessonTitle, TutorLastName, LessonTime, LessonStartDate, LessonEndDate)> 
<!ELEMENT LessonTitle (#PCDATA)> 
<!ELEMENT TutorLastName (#PCDATA)> 
<!ELEMENT LessonTime (#PCDATA)> 
<!ELEMENT LessonStartDate (#PCDATA)> 
<!ELEMENT LessonEndDate (#PCDATA)>
<!ATTLIST lesson id CDATA #REQUIRED>

=== Zanzibarin/HTML.CSS.XML.Practice/XMLPractice1.2/lessons.xml
<?xml version = "1.0" encoding ="utf-8"?>
<!DOCTYPE lesson SYSTEM "lessons_DTD.dtd">
<lessons>
	<lesson id ="1">
		<LessonTitle>Технологии программирования</LessonTitle>
		<TutorLastName>Осипов</TutorLastName>
		<LessonTime>18:30</LessonTime>
		<LessonStartDate>27.09.2021</LessonStartDate>
		<LessonEndDate>14.10.2021</LessonEndDate>
	</lesson>
	<lesson id ="2">
		<LessonTitle>Введение в базы данных</LessonTitle>
		<TutorLastName>Ямщиков</TutorLastName>
		<LessonTime>18:30</LessonTime>
		<LessonStartDate>18.10.2021</LessonStartDate>
		<LessonEndDate>26.10.2021</LessonEndDate>
	</lesson>
	<lesson id ="3">
		<LessonTitle>Программирование на C#</LessonTitle>
		<TutorLastName>Третьяков</TutorLastName>
		<LessonTime>18:30</LessonTime>
		<LessonStartDate>02.11.2021</LessonStartDate>
		<LessonEndDate>24.11.2021</LessonEndDate>
	</lesson>
</lessons>
